apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-service
  namespace: esn-events
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-service
  template:
    metadata:
      labels:
        app: event-service
    spec:
      containers:
        - name: event-service
          image: esn-event-service:0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: event-service-config
            - secretRef:
                name: jwt-shared-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"

            limits:
              memory: "512Mi"
              cpu: "500m"

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 40
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 15

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes

            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres