apiVersion: v1
kind: ConfigMap
metadata:
  name: ticket-service-config
  namespace: esn-events

data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/esn_events
  SPRING_DATASOURCE_USERNAME: postgres

  EVENT_SERVICE_URL: http://event-service:8081/api/events/